# Generated by Django 4.1.2 on 2022-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_minimo', models.IntegerField(default=0)),
                ('telefono', models.CharField(max_length=200)),
            ],
        ),
    ]
