# Generated by Django 4.1.2 on 2022-10-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('detalle', models.TextField()),
                ('marca', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=255)),
                ('imagenes', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('precio', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=1)),
                ('unidad', models.CharField(max_length=200)),
                ('plural', models.CharField(max_length=200)),
                ('conStock', models.BooleanField()),
                ('oferta', models.BooleanField()),
                ('mostrarDetalle', models.BooleanField()),
                ('tags', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
