# Generated by Django 4.1.2 on 2022-10-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='conStock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='detalle',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='mostrarDetalle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='plural',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
