# Generated by Django 4.1.2 on 2022-10-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='plural',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
